services:
  redis:
    container_name: redisskyjov1
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes", "--replica-read-only", "no" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
